name = "mendix_widget_gleam"
version = "2.0.19"
target = "javascript"
description = "Build Mendix Pluggable Widgets with Gleam — no JSX, pure Gleam + FFI"
licences = ["Apache-2.0"]
repository = { type = "github", user = "GG-O-BP", repo = "MendixWidgetGleam" }

[javascript]
typescript_declarations = false
runtime = "node"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glendix = ">= 2.0.19 and < 3.0.0"
